In [1]:
import pandas as pd

In [34]:
# find . -iname '*.pdf' -exec pdfgrep -i "deep learning" {} + | awk '{ split($0,a,":"); print a[1]  }' | uniq | awk '{ split($0,a,"_"); printf "%s %s\n",a[1],a[2]  }' | uniq > deeplearning.txt

def readFile(column, filename):
    students_py = pd.DataFrame(columns=[column])
    file_python = open(filename, 'r')
    for name in file_python:
        #print name[3:]    
        students_py.loc[name[2:].split('\n')[0]] = [True]
    return students_py


allfiles = []

allfiles.append(readFile('python', '/Users/cerminar/Downloads/SUMM2018/python.txt'))
allfiles.append(readFile('ml', '/Users/cerminar/Downloads/SUMM2018/machinelearning.txt'))
allfiles.append(readFile('keras', '/Users/cerminar/Downloads/SUMM2018/keras.txt'))

allfiles.append(readFile('dl', '/Users/cerminar/Downloads/SUMM2018/deeplearning.txt'))
allfiles.append(readFile('datascience', '/Users/cerminar/Downloads/SUMM2018/datascience.txt'))

allfiles.append(readFile('tensorflow', '/Users/cerminar/Downloads/SUMM2018/tensorflow.txt'))

#allfiles.append(readFile('jupiter', '/Users/cerminar/Downloads/SUMM2018/jupiter.txt'))

allfiles.append(readFile('anomaly', '/Users/cerminar/Downloads/SUMM2018/anomaly.txt'))


students = pd.concat(allfiles, axis=1)   
    
students

,python,ml,keras,dl,datascience,tensorflow,anomaly
- Akshama,True,True,True,True,NaN,True,NaN
- Ayushman,True,True,NaN,True,True,True,NaN
ABBAS Saleh,True,NaN,NaN,NaN,NaN,NaN,NaN
ABDELHADI Nada,True,NaN,NaN,NaN,NaN,NaN,NaN
ABDELHAK Sara,True,True,NaN,NaN,True,NaN,NaN
ABDUKODIROV Farhodjon,True,True,NaN,NaN,NaN,NaN,NaN
ABDUL WAHAB,True,True,NaN,True,True,NaN,NaN
ABISMAIL Walid,True,True,True,True,True,True,NaN
ABLIAZOV Aleksei,True,True,NaN,NaN,NaN,NaN,NaN
ABOU ALI,True,True,NaN,NaN,True,NaN,NaN
ABUSAH Johnson,True,NaN,NaN,NaN,NaN,NaN,NaN
ACHEAMPONG Francisca,True,True,NaN,True,NaN,NaN,NaN
ACIKGOZ Ogulcan,True,NaN,NaN,NaN,NaN,NaN,NaN
ADALOGLOU Nikolaos,True,True,NaN,True,NaN,True,NaN
ADARSH Adarsh,NaN,True,NaN,NaN,NaN,NaN,NaN
ADHIKARI Bipul,NaN,True,NaN,NaN,NaN,True,NaN
AFZAL Muhammad,True,True,NaN,True,NaN,NaN,NaN
AGARWAL Achal,True,True,NaN,NaN,NaN,NaN,NaN
AGARWAL Nikita,NaN,True,NaN,NaN,NaN,NaN,NaN
AGARWAL Rohit,True,True,NaN,NaN,True,NaN,NaN
AGARWAL Shreya,True,True,NaN,NaN,True,NaN,NaN
AGARWALA Nikita,True,NaN,NaN,NaN,NaN,NaN,NaN
AGGARWAL Ananya,True,True,NaN,NaN,True,NaN,NaN
AGGARWAL Luv,True,True,NaN,NaN,True,True,NaN
AGGARWAL Paritosh,True,NaN,NaN,NaN,NaN,NaN,NaN
AGGARWAL Somyaa,True,True,True,True,True,NaN,True
AGRAWAL Abhishek,True,NaN,NaN,NaN,NaN,NaN,NaN
AGRAWAL Harsh,True,True,NaN,True,NaN,NaN,NaN
AGRAWAL Piyush,True,True,NaN,True,NaN,NaN,NaN
AHMAD Saad,True,NaN,NaN,NaN,NaN,True,NaN
...,...,...,...,...,...,...,...
YADAV Saurabh,True,NaN,NaN,NaN,True,NaN,NaN
YADAV Shruti,NaN,True,NaN,NaN,NaN,NaN,NaN
YADLAPALLI Anjani,True,True,NaN,True,NaN,NaN,NaN
YAGUBLU Kanan,True,NaN,NaN,NaN,NaN,NaN,NaN
YEBDA Sadia,True,True,NaN,NaN,NaN,NaN,NaN
YELLAPRAGADA Santoshi,True,True,NaN,True,True,NaN,NaN
YEUNG Kei,True,True,NaN,NaN,NaN,NaN,NaN
YOUSFI Abdelghafour,True,NaN,NaN,NaN,NaN,NaN,NaN
YSASI CILLERO,True,NaN,NaN,NaN,NaN,NaN,NaN
YU Zhi,True,True,NaN,NaN,NaN,NaN,NaN
YURCHENKO-TYTARENKO Anton,True,True,NaN,NaN,True,NaN,NaN
YURTKULU Bahadir,True,True,NaN,NaN,True,NaN,NaN
ZAFAR Hamza,True,True,NaN,NaN,True,True,NaN
ZAHID Hamna,True,NaN,NaN,NaN,NaN,NaN,NaN
ZAHID Ussama,True,True,NaN,True,NaN,True,NaN
ZAINOOR Mubashir,True,True,NaN,NaN,True,NaN,NaN
ZAMPIERI Luca,True,True,NaN,NaN,NaN,NaN,NaN
ZAPARAS Paschalis,True,NaN,NaN,NaN,NaN,NaN,NaN
ZARDI Francesco,True,NaN,NaN,NaN,NaN,NaN,NaN
ZARIF Niloofar,True,NaN,NaN,NaN,NaN,NaN,NaN
ZAVERI Kanksha,True,True,NaN,NaN,NaN,NaN,NaN
ZHAO Wen,True,True,NaN,NaN,NaN,NaN,NaN
ZHOU Shengyang,True,NaN,NaN,NaN,NaN,NaN,NaN
ZIA Muhammad,True,True,NaN,True,True,True,NaN
ZISOULI Nikolina,True,NaN,NaN,NaN,NaN,NaN,NaN
ZIVIANI Serena,True,True,NaN,NaN,NaN,NaN,NaN
ZLAHODA Adriana,True,NaN,NaN,NaN,NaN,NaN,NaN
ZOGRAFOU Artemis,True,True,NaN,NaN,NaN,NaN,NaN
ZULFIQAR Annus,True,True,NaN,True,NaN,True,NaN
ZUZELSKI Joel,True,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
students[((students.ml==True) | (students.datascience==True)) & 
         (students.python==True) & 
         (students.keras==True) & 
         (students.tensorflow==True) &
          (students.anomaly == True)]
#.to_csv('/Users/cerminar/Downloads/SUMM2018/selection.txt')

                python    ml keras    dl datascience tensorflow anomaly
AJITH KUMAR       True  True  True  True         NaN       True    True
FAJARDO FAJARDO   True  True  True  True         NaN       True    True
GOEL Piyush       True  True  True  True         NaN       True    True
GUPTA Akshita     True  True  True  True         NaN       True    True
HUSSAIN Aman      True  True  True  True         NaN       True    True
KHAN Muhammad     True  True  True  True         NaN       True    True
SINGH Ayush       True  True  True  True        True       True    True